# Generated by Django 4.2.1 on 2023-05-27 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('skill', models.CharField(max_length=1000)),
                ('bio', models.TextField(max_length=5000)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
