# Generated by Django 4.2.1 on 2023-06-02 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('public_id', models.CharField(default=uuid.UUID('3f328f2d-cb9b-447a-92ec-fed82e9d5ba6'), max_length=300)),
                ('username', models.CharField(default='<django.db.models.fields.CharField>-<django.db.models.fields.CharField>', max_length=30, unique=True)),
                ('skills', models.CharField(max_length=1000)),
                ('bio', models.TextField(max_length=5000)),
                ('instagram', models.URLField(blank=True, default='', null=True)),
                ('twitter', models.URLField(blank=True, default='', null=True)),
                ('linkedin', models.URLField(blank=True, default='', null=True)),
                ('facebook', models.URLField(blank=True, default='', null=True)),
                ('phone', models.CharField(default='', max_length=30)),
                ('address', models.TextField(blank=True, default='', max_length=500, null=True)),
                ('whatsapp', models.URLField(blank=True, default='https://wa.me/55...', null=True)),
                ('cover', models.ImageField(default='', upload_to='hero-covers')),
                ('cover_url', models.URLField(blank=True, null=True)),
                ('cover_id', models.CharField(blank=True, default='', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUserModel',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hero_land.heromodel')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
        ),
    ]
