# Generated by Django 4.2.1 on 2023-06-02 14:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hero_land', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heromodel',
            name='public_id',
            field=models.CharField(default=uuid.UUID('ff796487-5d6c-4596-be57-f96e552fe211'), max_length=300),
        ),
        migrations.AlterField(
            model_name='heromodel',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
