# Generated by Django 4.2.1 on 2023-06-02 19:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hero_land', '0002_alter_heromodel_public_id_alter_heromodel_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heromodel',
            name='public_id',
            field=models.CharField(default=uuid.UUID('cbd51a80-6e2c-4732-96b9-f0ab610d1236'), max_length=300),
        ),
        migrations.AlterField(
            model_name='heromodel',
            name='whatsapp',
            field=models.URLField(blank=True, default='https://api.whatsapp.com/send/?phone=55...', null=True),
        ),
    ]
