# Generated by Django 4.2.1 on 2023-05-27 11:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hero_land', '0002_customuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='CustomUserModel',
        ),
        migrations.AlterModelManagers(
            name='customusermodel',
            managers=[
            ],
        ),
        migrations.RenameField(
            model_name='heromodel',
            old_name='skill',
            new_name='skills',
        ),
    ]
