# Generated by Django 4.2.1 on 2023-06-02 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hero_land', '0003_alter_heromodel_public_id_alter_heromodel_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='heromodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='heromodel',
            name='public_id',
            field=models.CharField(default=uuid.UUID('5eecb483-bcd8-463c-a91a-da13c1b51630'), max_length=300),
        ),
        migrations.DeleteModel(
            name='CustomUserModel',
        ),
    ]
