# Generated by Django 4.2.1 on 2023-06-01 10:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hero_land', '0003_rename_customuser_customusermodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='heromodel',
            name='public_id',
            field=models.CharField(default=uuid.UUID('36bc4fa3-fc40-4a63-8bbb-adec53208381'), max_length=300),
        ),
    ]
