# Generated by Django 4.2.1 on 2023-06-03 00:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hero_land', '0004_heromodel_user_alter_heromodel_public_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heromodel',
            name='cover',
            field=models.ImageField(blank=True, default='', null=True, upload_to='hero-covers'),
        ),
        migrations.AlterField(
            model_name='heromodel',
            name='public_id',
            field=models.CharField(default=uuid.UUID('ae216e17-2799-4c0d-97a8-16785dc3403c'), max_length=300),
        ),
    ]
