# Generated by Django 4.2.1 on 2023-06-01 12:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hero_land', '0004_heromodel_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heromodel',
            name='public_id',
            field=models.CharField(default=uuid.UUID('3f726fbe-52ce-4837-b3a3-cfb1de16f474'), max_length=300),
        ),
    ]
