# Generated by Django 4.2.1 on 2023-06-01 12:28

from django.db import migrations, models
import markdownfield.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hero_land', '0005_alter_heromodel_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heromodel',
            name='bio',
            field=markdownfield.models.MarkdownField(rendered_field='text_rendered'),
        ),
        migrations.AlterField(
            model_name='heromodel',
            name='public_id',
            field=models.CharField(default=uuid.UUID('b9d8f0f5-3d6f-4b79-9e37-796ba2df81e5'), max_length=300),
        ),
    ]
