# Generated by Django 4.2.1 on 2023-06-03 17:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hero_land', '0006_thememodel_alter_heromodel_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='heromodel',
            name='theme',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='hero_land.thememodel'),
        ),
        migrations.AddField(
            model_name='thememodel',
            name='font_color',
            field=models.CharField(default='#000000', max_length=20),
        ),
        migrations.AlterField(
            model_name='heromodel',
            name='public_id',
            field=models.CharField(default=uuid.UUID('5a05faee-b374-4a2f-b3dc-1c123451e167'), max_length=300),
        ),
    ]
