# Generated by Django 4.2.1 on 2023-06-01 12:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hero_land', '0007_heromodel_bio_rendered_alter_heromodel_bio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heromodel',
            name='bio_rendered',
        ),
        migrations.AlterField(
            model_name='heromodel',
            name='bio',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='heromodel',
            name='public_id',
            field=models.CharField(default=uuid.UUID('507135bf-5e62-4f1f-8a1e-25f841041ee4'), max_length=300),
        ),
    ]
