# Generated by Django 4.2.1 on 2023-06-06 21:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hero_land', '0007_heromodel_theme_thememodel_font_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heromodel',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='heromodel',
            name='public_id',
            field=models.CharField(default=uuid.UUID('4bf741d0-1877-4b50-b658-54d99d11e9ba'), max_length=300),
        ),
    ]
