# Generated by Django 4.2.1 on 2023-06-01 13:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hero_land', '0008_remove_heromodel_bio_rendered_alter_heromodel_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='heromodel',
            name='address',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='heromodel',
            name='facebook',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='heromodel',
            name='instagram',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='heromodel',
            name='linkedin',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='heromodel',
            name='phone',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='heromodel',
            name='twitter',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='heromodel',
            name='whatsapp',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='heromodel',
            name='public_id',
            field=models.CharField(default=uuid.UUID('943e01bf-40d0-4476-9071-de7d6b83c3e0'), max_length=300),
        ),
    ]
