# Generated by Django 4.2.1 on 2023-06-01 13:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hero_land', '0009_heromodel_address_heromodel_facebook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heromodel',
            name='public_id',
            field=models.CharField(default=uuid.UUID('cbeca5be-6afe-4652-b8d9-878ab0ca3da9'), max_length=300),
        ),
        migrations.AlterField(
            model_name='heromodel',
            name='whatsapp',
            field=models.URLField(default='https://wa.me/<django.db.models.fields.CharField>'),
        ),
    ]
